version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local_postgres_commerce
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: dnflskfk
      POSTGRES_DB: devdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
