CREATE SCHEMA IF NOT EXISTS "commerce";

CREATE TABLE IF NOT EXISTS "company" (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_yn BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "category" (
    id BIGSERIAL PRIMARY KEY,
    company_id BIGSERIAL NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_yn BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS "keyword" (
    id BIGSERIAL PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    del_yn BOOLEAN DEFAULT FALSE
);

