spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=commerce&utf8Encoding=true
    username: commerce
    password: dnflskfk
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariPool
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

